# ==============================================================================
# om_calibrate_luy.R
#
# Derives context-specific Luy calibration tables -- W(n), a(n), b(n) and the
# surviving-parent -> all-parent mean-age conversion -- from user-supplied
# fertility, population and mortality data.
#
# The algorithm was reverse-engineered from Luy's own calculation workbooks
# ("Multipliers_Italy_<year>_<SEX>_NEW_REF_YEARS.xls", which produce Tables
# A.5-A.20 of Luy 2009, EDRP 2009-3). Validation against those workbooks:
#   * .luy_engine() fed with Luy's own weights and q matrices reproduces his
#     reference periods exactly, MAC tables exactly, W(n) to a mean absolute
#     error of 2e-4 to 1e-3 (max. 1.2 % in the most extreme cells), a(n) and
#     b(n) to ~0.01 on average;
#   * the full pipeline on Luy's ISTAT inputs (1998, mothers) reproduces W(n)
#     to a mean absolute error of 0.001 (max. 2 %).
#
# ------------------------------------------------------------------------------
# WHAT LUY'S WORKBOOKS DO (respondent age group n, survey date T,
# K = n + 3 years of exposure, parental ages x = 15..49 mothers, 19..53 fathers)
# ------------------------------------------------------------------------------
# 1. Fertility schedule (sheet "Standards" + Schmertmann workbook).
#    * Empirical ASFR averaged over the respondents' five birth years
#      floor(T)-n-5 ... floor(T)-n-1 (e.g. 1933-37 for n = 60, T = 1998.5).
#    * Schmertmann (2003) parameters are READ OFF the schedule
#      ("graphically intuitive" parameters), not fitted: P = age with the
#      highest rate, f(P) = that rate, H = linearly interpolated age above P
#      at which the rate falls to f(P)/2; alpha = 14.
#    * The QS curve is evaluated as a POINT DENSITY phi(x) at integer x and
#      used as the rate of completed age x (not integrated over [x, x+1)).
#      This, plus measuring the mean at x + 0.5, is what the former
#      empirical "age_offset = 1" was compensating for.
#    * The mean age at childbearing is population weighted:
#      sum (x+0.5) N(x) f(x) / sum N(x) f(x).
#    * The baseline QS schedule is moved to the nearest integer mean with the
#      Brass relational Gompertz model F*(x) = exp(-exp(-(a + Y(x)))),
#      Y(x) = -ln(-ln F(x)), i.e. F* = F^exp(-a). Other target means are
#      reached by stepping P and H (up: +2/+1 per year, down: -1/-2, smaller
#      steps near the extremes) and fine-tuning with the same Gompertz model.
#    * Fathers: the female schedule is built on the female age scale (alpha
#      = 14, spline end beta capped at 50) and relabelled 4 years older
#      (Luy reports this as alpha = 18).
# 2. Mixed parental survival (rows 91-761 of each age-group sheet).
#    q[x, k] = cohort probability of dying at age x+k-1 of the cohort born in
#    floor(T) - n - 4 - x (ISTAT generation tables), k = 1..K.
#    The survival of "the" parents is built from the WEIGHTED AVERAGE OF THE
#    PROBABILITIES OF DYING with fixed weights w(x):
#        qbar_k = sum_x w(x) q[x, k],   L_k = prod_{j<=k} (1 - qbar_j),
#    and S_model = L_K. The weights are NOT re-normalised to the survivors,
#    i.e. this is not sum_x w(x) l_x(k). At old respondent ages the two differ
#    by a factor 2-3 (n = 60) -- this is the main reason a "correct" mixture
#    cannot reproduce Luy's W(n). mixing = "exact" gives the proper mixture.
#    Ages for which a cohort has no data (after the end of its series, e.g.
#    beyond the open age interval of an extinct cohort) are kept as NA and
#    the average in year k is taken over the cohorts observed in that year,
#    qbar_k = sum_obs w(x) q[x,k] / sum_obs w(x). Luy's workbooks instead
#    filled these cells with q = 0 (1998) or q = 1 (2003); either value
#    makes unobserved ages contribute to qbar_k. The package does neither.
#    w(x) = f(x)/sum f            in Luy (2009), Tables A.5-A.20;
#    w(x) = N(x) f(x) / sum N f   in the August 2010 supplement (Tables
#                                 A.5a-A.20a), used by the built-in
#                                 coefficients.
# 3. Reference period ("NEW REF YEARS"): mean time of the reconstructed deaths
#    D_k = L_{k-1} qbar_k, measured at mid-year,
#        tbar = sum D_k (k - 0.5) / sum D_k,   ref = T - K + tbar,
#    so t(n) = T - ref = K - tbar.
# 4. Period life table at the fractional year ref: l(x) interpolated linearly
#    between the calendar-year tables y = floor(ref) and y + 1 (sheet
#    LT_Berechnung).
# 5. W(n) = [l(33+n)/l(30)]_ref / S_model. No re-levelling to the observed
#    S(n) is involved.
# 6. a(n), b(n): mortality scenarios are generated by re-levelling the mixed
#    survival curve with Brass's logit model (beta = 1) to S_model * c,
#    c = 0.5, 0.55, ..., 1.5; t(n) = a(n) ln S + b(n) is fitted by OLS. The
#    scenario design is not in the workbooks; this choice reproduces Luy's
#    published a(n) and b(n) to ~0.01 on average.
# 7. Mean age at childbirth of ALL parents given the mean of SURVIVING parents
#    m (Tables A.5-A.8; needed when, as in the Italian MPS, the age at birth is
#    only known for living parents):
#        MAC(m) = sum_k L_{k-1} sum_x (x+0.5) w(x) q[x,k]  +  m * L_K.
#    W(n), a(n), b(n) are indexed by the mean age of ALL parents; convert the
#    survey's surviving-parent mean with this table before looking them up.
# ==============================================================================

#' @importFrom stats uniroot lm coef aggregate complete.cases optim
#' @keywords internal
NULL

#' Derive Context-Specific Luy Calibration Coefficients
#'
#' Derives population-specific weighting factors \eqn{W(n)}, reference-date
#' parameters \eqn{a(n)}, \eqn{b(n)} and the surviving-parent to all-parent
#' mean-age conversion for the Luy orphanhood method, reproducing the
#' calculation workbooks behind Luy (2009, 2010 supplement) and Luy (2012).
#'
#' @details
#' For each respondent age group \eqn{n} (exposure \eqn{K = n + 3} years) and
#' each target mean age at childbearing \eqn{M}:
#' \enumerate{
#'   \item The empirical ASFR of the respondents' five birth years is averaged
#'     and summarised by Schmertmann's graphical parameters (\eqn{P},
#'     \eqn{f(P)}, \eqn{H}, \eqn{\alpha = 14}; fathers: rates shifted by
#'     \code{male_shift} years, \eqn{\alpha = 18}). The quadratic-spline
#'     schedule is moved to \eqn{M} -- measured as \eqn{\sum (x+0.5) N_x f_x /
#'     \sum N_x f_x} -- by stepping \eqn{P}, \eqn{H} and fine-tuning with the
#'     Brass relational Gompertz model.
#'   \item The parental cohorts' probabilities of dying are averaged with
#'     fixed weights \eqn{w_x} and chained into a survival curve \eqn{L_k};
#'     \eqn{S = L_K}.
#'   \item \eqn{t(n)} is the mean time before the survey of the reconstructed
#'     deaths; the reference period is \eqn{T - t(n)}.
#'   \item \eqn{W(n) = [l(33+n)/l(30)]_{T - t(n)} / S}.
#'   \item \eqn{a(n)}, \eqn{b(n)} come from regressing \eqn{t(n)} on
#'     \eqn{\ln S} across logit-relevelled mortality scenarios.
#' }
#'
#' \strong{Weights.} \code{weighting = "Nf"} (default) uses \eqn{w_x \propto
#' N_x f_x} as in the 2010 supplement and in the package's built-in
#' coefficients; \code{"f"} uses \eqn{w_x \propto f_x} as in Luy (2009).
#'
#' \strong{Mixing.} \code{mixing = "luy"} (default) averages the
#' probabilities of dying with weights fixed at the respondents' birth, as
#' Luy's workbooks do. \code{"exact"} mixes the cohort survival curves,
#' \eqn{\sum_x w_x l_x(k)}, which is the demographically exact proportion of
#' parents alive; the two diverge strongly at older respondent ages, so only
#' \code{"luy"} reproduces the published tables.
#'
#' \strong{Parental cohorts (\code{cohort_lag}).} Respondents aged \eqn{n}
#' to \eqn{n+4} at the survey were born in the five calendar years
#' \eqn{\lfloor T \rfloor - n - 5} to \eqn{\lfloor T \rfloor - n - 1}.
#' Luy (2009, pp. 10 and 16) approximates their parents by the parents who
#' gave birth in the middle of these five years, \eqn{\lfloor T \rfloor - n
#' - 3}; in his calculation workbooks a parent aged \eqn{x} (completed
#' years) at that birth belongs to the cohort born in \eqn{\lfloor T
#' \rfloor - n - 3 - x - 1}. Hence the parental cohort is
#' \deqn{c(x, n) = \lfloor T \rfloor - n - \mathrm{cohort\_lag} - x,
#' \qquad \mathrm{cohort\_lag} = 4,}
#' and \eqn{q[x, k]} is the probability of dying of cohort \eqn{c(x, n)}
#' at age \eqn{x + k - 1}, i.e. in calendar year \eqn{\lfloor T \rfloor -
#' n - 4 + k - 1}, for \eqn{k = 1, \dots, K} with \eqn{K = n + 3} (Luy
#' 2009, p. 10: exposure of \eqn{n + 2.5} years plus the time of the
#' interview within the survey year).
#'
#' \strong{Unobserved ages.} No closure rule is applied to the cohort
#' series. A probability of dying that is not in \code{cohort_qx} (e.g. ages
#' beyond the last age of a cohort's table, such as the open interval
#' 110+) is kept as \code{NA} and gets no weight: in each year \eqn{k}
#' the weighted average of the probabilities of dying is taken over the
#' cohorts observed in that year,
#' \deqn{\bar q_k = \sum_{x \in O_k} v_{x,k} q[x,k] / \sum_{x \in O_k}
#' v_{x,k},}
#' with \eqn{v_{x,k} = w_x} (\code{mixing = "luy"}) or \eqn{v_{x,k} = w_x
#' l_x(k-1)} (\code{mixing = "exact"}). This distinguishes the absence of
#' observations from a probability of dying of 0 and prevents unobserved
#' ages from contributing to the calculation. Luy's workbooks filled these
#' cells with \eqn{q = 0} (1998 survey) or \eqn{q = 1} (2003 survey). If no
#' parental cohort is observed in some year \eqn{k} (data that end before
#' the calendar year \eqn{\lfloor T \rfloor - 2}), \eqn{S}, \eqn{W(n)},
#' \eqn{a(n)} and \eqn{b(n)} are \code{NA}. The share of the weights
#' observed in each year is returned in the intermediates
#' (\code{om_luy_intermediates(cal, "w_observed")}). In a complete cohort
#' life table the last, open age interval (e.g. 110+) has \eqn{q = 1}: the
#' cohort is extinct and no older age is needed.
#'
#' \strong{How closely Luy is reproduced.} Fed with Luy's own schedules and
#' cohort probabilities, the calculation reproduces his published
#' \eqn{W(n)} (Luy 2009) to within about 1\% and his reference periods
#' exactly. Run on independent data (e.g. HMD/HFD for Italy), the
#' differences from the built-in tables are below about 1\% up to
#' \eqn{n = 40}, a few per cent at \eqn{n = 45}--55 and larger at
#' \eqn{n = 60}, where Luy's values depend on how he filled the ages after
#' the end of the cohort series (see above) and on his source tables ending
#' around age 100. Treat the \eqn{n \ge 55} coefficients with caution.
#'
#' \strong{Mean age of all vs. surviving parents.} The tables are indexed by
#' the mean age at childbearing of \emph{all} parents. If your survey only
#' records the parent's age for living parents, convert it first with the
#' returned \code{mac} table (survivors' mean in the column header, all
#' parents' mean in the cells), as Luy does with his Tables A.5-A.8.
#'
#' @param sex_parent Character. \code{"Female"} or \code{"Male"}.
#' @param asfr Data frame of \strong{period} age-specific fertility rates of
#'   \strong{women}. Required columns: \code{age} (completed age, integer),
#'   \code{year} (calendar year, integer), \code{rate} (births per woman per
#'   year, numeric, \emph{not} per 1000). Needed for ages 15--49 in the
#'   respondents' birth years (see \code{\link{om_luy_data_needs}}).
#'   Period rates are required because the weights describe the mothers giving
#'   birth in a given calendar year. For fathers the female rates are shifted by
#'   \code{male_shift} (pass male rates with \code{male_shift = 0}).
#' @param cohort_qx Data frame of \strong{cohort} probabilities of dying of
#'   the parent's sex. Required columns: \code{age} (completed age, integer),
#'   \code{cohort} (birth year, integer), \code{qx} (probability 0-1, numeric).
#'   Must cover the parental cohorts up to calendar year
#'   \eqn{\lfloor T \rfloor - 2}, including cohorts still alive (see
#'   \code{\link{om_luy_data_needs}}); published cohort life tables usually
#'   exist only for extinct cohorts, so younger cohorts are typically built
#'   from cohort death rates. Ages not supplied are treated as unobserved
#'   (see Details). Used for q[x,k]; also for period tables when
#'   \code{period_lx} is not given.
#' @param pop_age Data frame of \strong{population size} (not exposure) of
#'   the parent's sex. Optional; if provided, requires columns \code{age}
#'   (completed age, integer), \code{year} (calendar year, integer), \code{n}
#'   (population count, numeric). Averaged over the respondents' birth years;
#'   enters the mean age at childbearing and, with \code{weighting = "Nf"},
#'   the weights. If \code{NULL}, \eqn{N_x = 1} (with a message).
#' @param survey_date Numeric. Interview date as a decimal year (\eqn{T}),
#'   e.g. 1998.5.
#' @param age_respondent Numeric vector of respondent age group lower bounds.
#' @param mean_age_grid Numeric vector of (integer) mean ages at
#'   childbearing. Defaults to 22:35 (mothers) and 24:37 (fathers), as in Luy.
#' @param period_lx Optional data frame of \strong{period} life tables of
#'   the parent's sex, columns \code{year}, \code{age}, and \code{lx} (or
#'   \code{qx}). Recommended (e.g. HMD \code{fltper_1x1}). If \code{NULL}, period
#'   tables are assembled from the diagonals of \code{cohort_qx}.
#' @param weighting \code{"Nf"} (2010 supplement, default) or \code{"f"}
#'   (Luy 2009).
#' @param mixing \code{"luy"} (default, reproduces Luy) or \code{"exact"}.
#' @param smoothing \code{"graphical"} (default; Schmertmann parameters read
#'   off the empirical schedule, as Luy did) or \code{"lsq"} (least-squares
#'   fit of the QS point densities, more robust for noisy rates).
#' @param cohort_lag Integer, default 4 (Luy 2009). Years subtracted, in
#'   addition to \eqn{n} and \eqn{x}, from the survey year to obtain the
#'   birth cohort of a parent aged \eqn{x} at the respondent's birth:
#'   \code{cohort = floor(survey_date) - n - cohort_lag - x}. The value 4
#'   combines the 3 years between \eqn{\lfloor T \rfloor - n} and the middle
#'   of the respondents' five birth years (\eqn{\lfloor T \rfloor - n - 3},
#'   Luy 2009, pp. 10, 16) and 1 year for the parent's completed age
#'   \eqn{x}, as in Luy's calculation workbooks. It also fixes the first
#'   calendar year of exposure, \eqn{\lfloor T \rfloor - n - 4}. See
#'   Details.
#' @param male_shift Numeric. Years by which female ASFR are shifted to
#'   obtain paternal schedules (Luy: 4).
#' @param age_range Numeric length-2 vector, youngest and oldest parental age.
#'   Defaults to \code{c(15, 49)} (mothers) and \code{c(15, 49) + male_shift}
#'   (fathers).
#' @param s_factors Numeric vector of multipliers applied to the model
#'   \eqn{S(n)} to build the mortality scenarios used for \eqn{a(n)},
#'   \eqn{b(n)}.
#'
#' @return A named list with elements \code{"Female"} and \code{"Male"};
#'   the one matching \code{sex_parent} holds a list of four data frames
#'   (the other is \code{NULL}). Each data frame has one row per respondent
#'   age group (column \code{Age_Group} = \eqn{n}) and one column per mean
#'   age at childbearing in \code{mean_age_grid} (named \code{"22"},
#'   \code{"23"}, ...), the layout of the built-in coefficients, so that the
#'   result can be passed to \code{custom_coef_luy} in
#'   \code{\link{om_estimate_index}}:
#'   \describe{
#'     \item{\code{wn}}{weighting factors \eqn{W(n)}, with
#'       \eqn{l(33+n)/l(30) = S(n) W(n)} (Luy 2009, eq. 1; Tables A.9--A.12).}
#'     \item{\code{an}, \code{bn}}{reference-period parameters, with
#'       \eqn{t(n) = a(n) \ln S(n) + b(n)} years before the survey (Luy
#'       2009, Tables A.13--A.20).}
#'     \item{\code{mac}}{mean age at childbirth of all parents (cells) given
#'       the mean age of surviving parents (column names) (Luy 2009, Tables
#'       A.5--A.8).}
#'   }
#'   \code{NA} marks cells that could not be computed (see the warnings).
#'   Attributes:
#'   \describe{
#'     \item{\code{diagnostics}}{data frame, one row per age group and mean
#'       age: \code{Age_Group}, \code{mean_age}, model survival
#'       \code{S_model}, reference year \code{ref_year}, \code{t_n},
#'       \code{W}, Brass-Gompertz \code{gompertz_alpha}, Schmertmann
#'       \code{P} and \code{H}, and \code{weight_dropped} (share of the
#'       weights of parental cohorts absent from \code{cohort_qx}).}
#'     \item{\code{intermediates}}{list by age group with every intermediate
#'       quantity of the calculation, laid out like Luy's workbooks; extract
#'       with \code{\link{om_luy_intermediates}}.}
#'     \item{\code{settings}}{list of the arguments used.}
#'   }
#'
#' @references
#' Luy, M. (2009). Estimating mortality differentials in developed
#' populations from survey information on maternal and paternal orphanhood.
#' \emph{European Demographic Research Papers} 2009-3; supplement, August
#' 2010.
#'
#' Luy, M. (2012). Estimating mortality differences in developed countries
#' from survey information on maternal and paternal orphanhood.
#' \emph{Demography}, 49(2), 607-627.
#'
#' Schmertmann, C. P. (2003). A system of model fertility schedules with
#' graphically intuitive parameters. \emph{Demographic Research}, 9(5),
#' 81-110.
#'
#' @examples
#' # synthetic inputs in the standard long format
#' asfr <- expand.grid(age = 15:49, year = 1950:2000)
#' asfr$rate <- 0.1 * exp(-0.5 * ((asfr$age - 28) / 5.5)^2)
#' cohort_qx <- expand.grid(age = 0:110, cohort = 1900:1990)
#' cohort_qx$qx <- pmin(1, 0.00005 * exp(0.095 * cohort_qx$age))
#' cohort_qx <- cohort_qx[cohort_qx$cohort + cohort_qx$age <= 2003, ]
#' pop_age <- expand.grid(age = 0:110, year = 1950:2000)
#' pop_age$n <- 1e5 * exp(-0.01 * pop_age$age)
#' period_lx <- expand.grid(age = 0:110, year = 1980:2003)
#' period_lx$lx <- 1e5 * exp(-0.00005 / 0.095 * (exp(0.095 * period_lx$age) - 1))
#'
#' cal <- om_calibrate_luy("Female", asfr = asfr, cohort_qx = cohort_qx,
#'                         pop_age = pop_age, period_lx = period_lx,
#'                         survey_date = 2003.9, age_respondent = c(20, 40))
#' cal$Female$wn    # W(n)
#' cal$Female$mac   # mean age of all parents given that of surviving parents
#'
#' # use the coefficients in the estimation
#' est <- om_estimate_index(method = "luy", sex_parent = "Female",
#'                          age_respondent = c(20, 40), p_surv = c(0.95, 0.75),
#'                          mean_age_parent = 27, surv_date = 2003.9,
#'                          custom_coef_luy = cal)
#' est$estimates
#'
#' @seealso \code{\link{om_estimate_index}}, \code{\link{om_luy_intermediates}},
#'   \code{\link{om_luy_data_needs}}
#'
#' @export
om_calibrate_luy <- function(sex_parent,
                             asfr,
                             cohort_qx,
                             pop_age        = NULL,
                             survey_date,
                             age_respondent = seq(20, 60, by = 5),
                             mean_age_grid  = NULL,
                             period_lx      = NULL,
                             weighting      = c("Nf", "f"),
                             mixing         = c("luy", "exact"),
                             smoothing      = c("graphical", "lsq"),
                             cohort_lag     = 4,
                             male_shift     = 4,
                             age_range      = NULL,
                             s_factors      = seq(0.5, 1.5, by = 0.05)) {
  sex_parent <- match.arg(sex_parent, c("Female", "Male"))
  weighting  <- match.arg(weighting)
  mixing     <- match.arg(mixing)
  smoothing  <- match.arg(smoothing)
  if (is.null(asfr) || is.null(cohort_qx)) {
    stop("'asfr' and 'cohort_qx' are required.", call. = FALSE)
  }
  # same checks as om_luy_validate_inputs(): columns, numeric whole keys,
  # no duplicated keys, rates per woman, q between 0 and 1
  om_luy_validate_inputs(asfr = asfr, cohort_qx = cohort_qx,
                         pop_age = pop_age, period_lx = period_lx,
                         verbose = FALSE)
  if (is.null(pop_age)) {
    message("No 'pop_age' supplied: N(x) = 1, i.e. the mean age at ",
            "childbearing is the mean of the rates and weights use f(x) only.")
  }

  shift <- if (sex_parent == "Male") male_shift else 0
  if (is.null(age_range)) age_range <- c(15, 49) + shift
  if (is.null(mean_age_grid)) {
    mean_age_grid <- if (sex_parent == "Female") 22:35 else 24:37
  }
  ages_x   <- seq(age_range[1], age_range[2])
  Tfloor   <- floor(survey_date)

  qx_get <- .luy_index_qx(cohort_qx)
  lx_at  <- .luy_period_lx_fun(period_lx, qx_get)

  nR <- length(age_respondent); nC <- length(mean_age_grid)
  wn <- an <- bn <- mac <- matrix(NA_real_, nR, nC)
  diag_list <- list(); sched_list <- list()

  for (i in seq_len(nR)) {
    n   <- age_respondent[i]
    K   <- as.integer(n + 3)
    yrs <- seq(Tfloor - n - 5, Tfloor - n - 1)

    # -- Step 1: fertility schedules ----------------------------------------
    f_emp <- .luy_avg(asfr, "rate", yrs, ages_x - shift)
    if (all(f_emp == 0)) {
      warning(sprintf("No 'asfr' for years %d-%d; age group %d skipped.",
                      min(yrs), max(yrs), n), call. = FALSE)
      next
    }
    N <- if (is.null(pop_age)) rep(1, length(ages_x)) else
      .luy_avg(pop_age, "n", yrs, ages_x)
    if (sum(N) <= 0) N <- rep(1, length(ages_x))

    # Fathers: Luy builds the QS schedule on the female age scale (alpha =
    # 14, spline cap beta <= 50) and relabels it to ages x + male_shift, so
    # the schedule is modelled on ages_x - shift and only the mean (and N)
    # use the paternal ages.
    fs <- .luy_schedules(ages_x - shift, f_emp, N, mean_age_grid - shift,
                         alpha_qs = 14, smoothing = smoothing)
    fs$params$P <- fs$params$P + shift
    fs$params$H <- fs$params$H + shift
    w <- if (weighting == "Nf") fs$f * N else fs$f
    w <- sweep(w, 2, colSums(w), "/")
    f_prime <- fs$f                                  # f(x)/sum f, Luy's "MODELED f(x)/TFR"

    # -- Step 2: probabilities of dying of the parental cohorts --------------
    q <- matrix(NA_real_, length(ages_x), K)
    for (a in seq_along(ages_x)) {
      x  <- ages_x[a]
      qq <- qx_get(x:(x + K - 1L), Tfloor - n - cohort_lag - x)
      if (!is.null(qq)) q[a, ] <- qq
    }
    # a cohort with no data at all gets no weight; single unobserved
    # q[x, k] stay NA and are excluded year by year in .luy_engine()
    miss <- rowSums(!is.na(q)) == 0L
    if (all(miss)) {
      warning(sprintf("No cohort mortality for age group %d.", n),
              call. = FALSE)
      next
    }
    if (any(miss)) {
      warning(sprintf(paste0("Age group %d: no cohort q(x) for parental ",
                             "ages %s (cohorts %s); their weight is dropped."),
                      n, paste(range(ages_x[miss]), collapse = "-"),
                      paste(range(Tfloor - n - cohort_lag - ages_x[miss]),
                            collapse = "-")),
              call. = FALSE)
    }

    # -- Steps 3-7 -----------------------------------------------------------
    w_ok <- w[!miss, , drop = FALSE]
    w_ok <- sweep(w_ok, 2, colSums(w_ok), "/")
    eng <- .luy_engine(w_ok, q[!miss, , drop = FALSE],
                       ages = ages_x[!miss], n = n, survey_date = survey_date,
                       lx_at = lx_at, acb = mean_age_grid,
                       s_factors = s_factors, mixing = mixing)
    no_S <- !is.finite(eng$S)
    if (any(no_S)) {
      warning(sprintf(paste0("Age group %d: no parental survival for mean ",
                             "age(s) %s -- in some year of exposure no ",
                             "parental cohort is observed (cohort_qx must ",
                             "reach calendar year %d). W(n), a(n), b(n) set ",
                             "to NA."), n,
                      paste(mean_age_grid[no_S], collapse = ", "),
                      Tfloor - 2L), call. = FALSE)
    }
    bad_W <- is.finite(eng$S) & (!is.finite(eng$W) | eng$W <= 0 | eng$W > 50)
    if (any(bad_W)) {
      warning(sprintf(paste0("Age group %d: W(n) not computable or ",
                             "implausible for mean age(s) %s (check ",
                             "'period_lx' at ages 30 and %d around the ",
                             "reference period); set to NA."), n,
                      paste(mean_age_grid[bad_W], collapse = ", "), 33 + n),
              call. = FALSE)
      eng$W[bad_W] <- NA_real_
    }
    wn[i, ] <- eng$W; an[i, ] <- eng$a; bn[i, ] <- eng$b; mac[i, ] <- eng$mac

    dn <- list(as.character(ages_x), as.character(mean_age_grid))
    sched_list[[as.character(n)]] <- list(
      n = n, K = K, birth_years = yrs,
      ages = ages_x, cohorts = Tfloor - n - cohort_lag - ages_x,
      f_empirical = stats::setNames(f_emp, ages_x),
      N = stats::setNames(N, ages_x),
      f_prime = structure(f_prime, dimnames = dn),
      weights = structure(w, dimnames = dn),
      q = structure(q, dimnames = list(as.character(ages_x), as.character(seq_len(K)))),
      q_bar = structure(eng$q_bar, dimnames = list(as.character(seq_len(K)), dn[[2]])),
      L = structure(eng$L, dimnames = list(as.character(0:K), dn[[2]])),
      w_observed = structure(eng$w_observed,
                             dimnames = list(as.character(seq_len(K)), dn[[2]])),
      summary = data.frame(mean_age = mean_age_grid, S_model = eng$S,
                           ref_year = eng$ref, t_n = eng$t_n,
                           lx_ratio = eng$lx_ratio, W = eng$W, mac = eng$mac,
                           P = fs$params$P, H = fs$params$H,
                           gompertz_alpha = fs$params$gompertz_alpha))

    diag_list[[length(diag_list) + 1L]] <- data.frame(
      Age_Group = n, mean_age = mean_age_grid, S_model = eng$S,
      ref_year = eng$ref, t_n = eng$t_n, W = eng$W,
      gompertz_alpha = fs$params$gompertz_alpha,
      P = fs$params$P, H = fs$params$H,
      weight_dropped = 1 - colSums(w[!miss, , drop = FALSE]))
  }

  build <- function(mat) {
    df <- as.data.frame(mat); names(df) <- as.character(mean_age_grid)
    cbind(Age_Group = age_respondent, df)
  }
  out <- list(Female = NULL, Male = NULL)
  out[[sex_parent]] <- list(wn = build(wn), an = build(an), bn = build(bn),
                            mac = build(mac))
  attr(out, "diagnostics") <- if (length(diag_list))
    do.call(rbind, diag_list) else NULL
  attr(out, "intermediates") <- sched_list
  attr(out, "settings") <- list(
    sex_parent = sex_parent, survey_date = survey_date,
    weighting = weighting, mixing = mixing, smoothing = smoothing,
    cohort_lag = cohort_lag, male_shift = male_shift,
    ages = ages_x, period_lx = if (is.null(period_lx)) "cohort diagonal"
                               else "user")
  out
}


# ------------------------------------------------------------------------------
# Core engine (Steps 2-7). Separated so it can be validated against Luy's own
# weight and q matrices.
# ------------------------------------------------------------------------------

#' Luy calibration engine
#'
#' @param w Matrix (parental ages x target mean ages) of weights, columns
#'   summing to one.
#' @param q Matrix (parental ages x K) of cohort probabilities of dying,
#'   \code{q[x, k]} referring to year \code{k} after the respondents' birth.
#' @param ages Parental ages (rows of \code{w} and \code{q}).
#' @param n Respondent age group lower bound.
#' @param survey_date Survey date (decimal year).
#' @param lx_at Function of a decimal year returning period \eqn{l(x)} at
#'   ages \code{0:max}.
#' @param acb Target mean ages (columns of \code{w}).
#' @param s_factors Scenario multipliers for \eqn{a(n)}, \eqn{b(n)}.
#' @param mixing \code{"luy"} or \code{"exact"}.
#' @return A list of vectors (one value per column): \code{S}, \code{t_n},
#'   \code{ref}, \code{W}, \code{a}, \code{b}, \code{mac}, \code{lx_ratio}
#'   (period l(33+n)/l(30) at \code{ref}), and matrices \code{q_bar}
#'   (K x columns), \code{L} ((K+1) x columns, \code{L[1, ] = 1}) and
#'   \code{w_observed} (K x columns, share of the weights whose
#'   \code{q[x, k]} is observed). \code{NA} entries of \code{q} are
#'   unobserved and get no weight.
#' @keywords internal
.luy_engine <- function(w, q, ages, n, survey_date, lx_at, acb,
                        s_factors = seq(0.5, 1.5, by = 0.05),
                        mixing = "luy") {
  K  <- ncol(q); M <- ncol(w)
  kk <- seq_len(K) - 0.5
  obs <- !is.na(q)                                  # observed q[x, k]
  q0  <- q; q0[!obs] <- 0                           # placeholder, never weighted
  # exact mixing: survival of each cohort at the start of year k
  # (NA once a cohort's series is no longer observed)
  lprev <- if (mixing == "exact")
    cbind(1, t(apply(1 - q, 1, cumprod)))[, seq_len(K), drop = FALSE] else NULL

  tbar_of <- function(L) {
    qb <- 1 - L[-1] / L[-(K + 1L)]
    D  <- L[-(K + 1L)] * qb
    sum(D * kk) / sum(D)
  }

  res <- list(S = rep(NA_real_, M), t_n = rep(NA_real_, M),
              ref = rep(NA_real_, M), W = rep(NA_real_, M),
              a = rep(NA_real_, M), b = rep(NA_real_, M),
              mac = rep(NA_real_, M), lx_ratio = rep(NA_real_, M),
              q_bar = matrix(NA_real_, K, M), L = matrix(NA_real_, K + 1L, M),
              w_observed = matrix(NA_real_, K, M))

  for (j in seq_len(M)) {
    # weight of cohort x in year k: fixed w(x) (Luy) or w(x) l_x(k-1)
    # (exact mixture). Unobserved q[x, k] get no weight: the average is
    # taken over the cohorts observed in year k, so ages without data do
    # not enter the calculation, neither as q = 0 nor as q = 1.
    v <- if (mixing == "luy") matrix(w[, j], nrow(q), K) else w[, j] * lprev
    v[!obs | is.na(v)] <- 0
    sv   <- colSums(v)
    qbar <- ifelse(sv > 0, colSums(v * q0) / sv, NA_real_)
    L    <- cumprod(c(1, 1 - qbar))
    res$w_observed[, j] <- colSums(w[, j] * obs)
    res$q_bar[, j] <- qbar; res$L[, j] <- L
    S <- L[K + 1L]
    if (!is.finite(S) || S <= 0 || S >= 1) next
    tb  <- tbar_of(L)
    ref <- survey_date - K + tb

    # mean age at childbirth of all parents, survivors' mean = acb[j]:
    # deaths in year k, L_{k-1} qbar_k, split by parental age x
    dx_age <- ifelse(sv > 0, colSums((ages + 0.5) * v * q0) / sv, 0)
    mac_j  <- sum(L[-(K + 1L)] * dx_age) + acb[j] * S

    lx <- lx_at(ref)
    Wj <- if (is.null(lx) || length(lx) < 34 + n) NA_real_ else
      (lx[34 + n] / lx[31]) / S                    # l(33+n)/l(30); index = age+1

    # a(n), b(n): logit-relevelled scenarios around S
    tg <- S * s_factors
    tg <- tg[tg > 0 & tg < 1]
    Y  <- 0.5 * log((1 - L[-1]) / L[-1])
    pts <- t(vapply(tg, function(s) {
      al <- 0.5 * log((1 - s) / s) - Y[K]
      Ls <- c(1, 1 / (1 + exp(2 * (al + Y))))
      c(log(s), K - tbar_of(Ls))
    }, numeric(2)))
    ab <- if (nrow(pts) >= 2L) stats::coef(stats::lm(pts[, 2] ~ pts[, 1]))
          else c(NA_real_, NA_real_)

    res$S[j] <- S; res$t_n[j] <- K - tb; res$ref[j] <- ref; res$W[j] <- Wj
    res$lx_ratio[j] <- Wj * S
    res$b[j] <- unname(ab[1]); res$a[j] <- unname(ab[2]); res$mac[j] <- mac_j
  }
  res
}


# ------------------------------------------------------------------------------
# Fertility schedules (Step 1)
# ------------------------------------------------------------------------------

#' Luy's model fertility schedules for a set of target mean ages
#'
#' @param ages Integer parental ages (completed age labels).
#' @param f_emp Empirical rates at \code{ages}.
#' @param N Population at \code{ages}.
#' @param grid Target mean ages at childbearing.
#' @param alpha_qs Schmertmann \eqn{\alpha}. Always 14: paternal schedules
#'   are modelled on the female age scale and relabelled by the caller.
#' @param smoothing \code{"graphical"} or \code{"lsq"}.
#' @param ph_path \code{"paper"} or \code{"closest"}; see the code comments.
#' @param baseline Optional integer mean age assigned to the baseline QS
#'   schedule (default: its rounded mean).
#' @return List with \code{f} (matrix ages x grid, columns sum to one) and
#'   \code{params} (P, H, Gompertz alpha per target).
#' @keywords internal
.luy_schedules <- function(ages, f_emp, N, grid, alpha_qs = 14,
                           smoothing = "graphical", ph_path = "paper",
                           baseline = NULL) {
  mean_N <- function(f) sum((ages + 0.5) * N * f) / sum(N * f)
  qs_at  <- function(P, H) {
    sp <- .qs_spline(alpha_qs, P, H)
    if (is.null(sp)) return(NULL)
    f <- .qs_phi(ages, sp)
    if (sum(f) <= 0) NULL else f / sum(f)
  }
  gomp <- function(f, a) {
    Fx <- cumsum(f) / sum(f)
    Fs <- Fx^exp(-a)                      # = exp(-exp(-(a + Y))), Y=-ln(-ln F)
    pmax(diff(c(0, Fs)), 0)
  }
  tune <- function(f, target) {
    g  <- function(a) mean_N(gomp(f, a)) - target
    a0 <- tryCatch(stats::uniroot(g, c(-3, 3), extendInt = "yes",
                                  tol = 1e-10)$root,
                   error = function(e) NA_real_)
    list(f = if (is.na(a0)) rep(NA_real_, length(f)) else gomp(f, a0),
         a = a0)
  }

  # graphical parameters (Schmertmann 2003; Luy reads them off the data)
  i  <- which.max(f_emp); P0 <- ages[i]; R <- f_emp[i]
  j  <- which(ages > P0 & f_emp < R / 2)[1]
  H0 <- if (is.na(j)) P0 + 8 else
    ages[j - 1] + (f_emp[j - 1] - R / 2) / (f_emp[j - 1] - f_emp[j])
  if (smoothing == "lsq") {
    sse <- function(p) {
      sp <- .qs_spline(alpha_qs, p[1], p[2])
      if (is.null(sp)) return(1e10)
      sum((p[3] * .qs_phi(ages, sp) - f_emp)^2)
    }
    fit <- stats::optim(c(P0, H0, R), sse, control = list(reltol = 1e-12,
                                                         maxit = 5000))
    P0 <- fit$par[1]; H0 <- fit$par[2]
  }
  base <- qs_at(P0, H0)
  if (is.null(base)) stop("Could not build a Schmertmann schedule.",
                          call. = FALSE)
  B <- if (is.null(baseline)) round(mean_N(base)) else baseline

  # P/H path from the baseline mean B to every target. Luy (2009, p. 14):
  # "For each year that the target mean was higher or lower than the base
  # mean, P and H were increased by 2.0 and 1.0, or decreased by 1.0 and 2.0
  # years". His workbooks shorten the last downward steps to -0.75/-1.5 and
  # -0.5/-1 (and the last upward ones to +1.5/+0.75, +1/+0.75) when P
  # approaches alpha or H approaches P. path = "paper" applies the full
  # steps while the spline stays well defined (P - alpha >= min_pa, H - P >=
  # min_hp) and otherwise the next smaller step; path = "closest" picks, at
  # every step, the increment whose QS mean is closest to the next integer.
  # (the pure translations at the end are fall-backs for narrow schedules)
  up   <- list(c(2, 1), c(1.5, 0.75), c(1, 0.75), c(1, 1), c(0.5, 0.5))
  down <- list(c(-1, -2), c(-0.75, -1.5), c(-0.5, -1), c(-0.25, -0.5),
               c(-1, -1), c(-0.5, -0.5))
  min_pa <- 4.5; min_hp <- 2.5
  path <- list(); path[[as.character(B)]] <- c(P0, H0)
  walk <- function(dir, to) {
    cur <- c(P0, H0); m <- B
    cand <- if (dir > 0) up else down
    while (m != to) {
      m <- m + dir
      best <- NULL; bd <- Inf
      for (st in cand) {
        ph <- cur + st
        if (ph[1] - alpha_qs < min(min_pa, cur[1] - alpha_qs) - 1e-9 ||
            ph[2] - ph[1] < min(min_hp, cur[2] - cur[1]) - 1e-9) next
        f <- qs_at(ph[1], ph[2]); if (is.null(f)) next
        if (ph_path == "paper") { best <- ph; break }
        d <- abs(mean_N(f) - m)
        if (d < bd) { bd <- d; best <- ph }
      }
      if (is.null(best)) best <- cur
      cur <- best; path[[as.character(m)]] <<- cur
    }
  }
  if (max(grid) > B) walk(+1, max(grid))
  if (min(grid) < B) walk(-1, min(grid))

  fm <- matrix(NA_real_, length(ages), length(grid))
  pr <- data.frame(target = grid, P = NA_real_, H = NA_real_,
                   gompertz_alpha = NA_real_)
  for (k in seq_along(grid)) {
    ph <- path[[as.character(round(grid[k]))]]
    if (is.null(ph)) ph <- c(P0, H0)
    f  <- qs_at(ph[1], ph[2])
    tu <- tune(f, grid[k])
    fm[, k] <- tu$f
    pr$P[k] <- ph[1]; pr$H[k] <- ph[2]; pr$gompertz_alpha[k] <- tu$a
  }
  list(f = sweep(fm, 2, colSums(fm), "/"), params = pr, baseline_mean = B)
}


# ------------------------------------------------------------------------------
# Data helpers
# ------------------------------------------------------------------------------

#' Average a (age, year, value) table over years at given ages
#' @param df Data frame with columns \code{age}, \code{year} and \code{col}.
#' @param col Name of the value column.
#' @param years,ages Years to average over and ages to return.
#' @return Numeric vector of averages at \code{ages} (0 where no data).
#' @keywords internal
.luy_avg <- function(df, col, years, ages) {
  d <- data.frame(age  = suppressWarnings(as.numeric(as.character(df$age))),
                  year = suppressWarnings(as.numeric(as.character(df$year))),
                  v    = suppressWarnings(as.numeric(as.character(df[[col]]))))
  d <- d[stats::complete.cases(d) & d$year %in% years & d$age %in% ages, ]
  if (nrow(d) == 0L) return(rep(0, length(ages)))
  a <- stats::aggregate(v ~ age, data = d, FUN = mean)
  out <- a$v[match(ages, a$age)]
  out[is.na(out)] <- 0
  out
}

#' Index cohort probabilities of dying
#'
#' No closure rule is applied: ages for which a cohort has no data (after
#' the end of its series, or not yet reached by calendar time) are returned
#' as \code{NA}, so that they never enter the calculation as a probability
#' of dying of 0 or 1.
#' @param cohort_qx Data frame with columns \code{age}, \code{cohort},
#'   \code{qx}.
#' @return A function \code{(age_vector, cohort)} returning the probabilities
#'   of dying (with \code{NA} for unobserved ages), or \code{NULL} if the
#'   cohort has no data at those ages.
#' @keywords internal
.luy_index_qx <- function(cohort_qx) {
  cq <- data.frame(
    age    = suppressWarnings(as.numeric(as.character(cohort_qx$age))),
    cohort = suppressWarnings(as.numeric(as.character(cohort_qx$cohort))),
    qx     = suppressWarnings(as.numeric(as.character(cohort_qx$qx))))
  cq <- cq[stats::complete.cases(cq), ]
  if (nrow(cq) == 0L) stop("'cohort_qx' has no usable rows.", call. = FALSE)
  a_max <- max(cq$age); c_min <- min(cq$cohort); c_max <- max(cq$cohort)
  mat <- matrix(NA_real_, a_max + 1L, c_max - c_min + 1L)
  mat[cbind(cq$age + 1L, cq$cohort - c_min + 1L)] <- cq$qx
  function(age_v, cohort) {
    if (cohort < c_min || cohort > c_max || min(age_v) < 0) return(NULL)
    v <- rep(NA_real_, length(age_v))
    in_tab <- age_v <= a_max
    v[in_tab] <- mat[age_v[in_tab] + 1L, cohort - c_min + 1L]
    if (all(is.na(v))) NULL else pmin(pmax(v, 0), 1)
  }
}

#' Period life table at a fractional year
#'
#' Luy (sheet LT_Berechnung) interpolates l(x) linearly between the tables of
#' calendar years \code{floor(t)} and \code{floor(t)+1}.
#' @return A function of a decimal year returning \eqn{l(x)} indexed by
#'   age + 1 (from the cohort diagonal only ages 30+ are filled), or NULL.
#' @keywords internal
.luy_period_lx_fun <- function(period_lx, qx_get) {
  if (!is.null(period_lx)) {
    pl <- period_lx
    if (!"lx" %in% names(pl)) {
      if (!"qx" %in% names(pl)) {
        stop("'period_lx' needs a column 'lx' or 'qx'.", call. = FALSE)
      }
      pl <- do.call(rbind, lapply(split(pl, pl$year), function(d) {
        d <- d[order(d$age), ]
        d$lx <- cumprod(c(1, 1 - d$qx))[seq_len(nrow(d))]
        d
      }))
    }
    pl <- pl[order(pl$year, pl$age), ]
    tabs <- lapply(split(pl, pl$year), function(d) {
      v <- rep(NA_real_, max(d$age) + 1L); v[d$age + 1L] <- d$lx; v
    })
    get_year <- function(y) tabs[[as.character(y)]]
  } else {
    # only l(30) and l(33+n) are needed: start the diagonal at age 30 so
    # that recent cohorts (young ages) are not required
    get_year <- function(y) {
      v <- c(rep(NA_real_, 30), 1)
      for (a in 30:129) {
        q <- qx_get(a, y - a)
        if (is.null(q) || is.na(q)) break
        v <- c(v, v[length(v)] * (1 - q))
      }
      if (length(v) < 32) NULL else v
    }
  }
  function(t) {
    y0 <- floor(t); fr <- t - y0
    l0 <- get_year(y0); l1 <- get_year(y0 + 1)
    if (is.null(l0)) return(NULL)
    if (is.null(l1) || fr == 0) return(l0)
    m <- min(length(l0), length(l1))
    (1 - fr) * l0[seq_len(m)] + fr * l1[seq_len(m)]
  }
}
